logging:
  level:
    root: info
    org.hibernate.jpa: info
    org.hibernate.sql: info
    org.hibernate.type: info

server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moasis
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

app:
  image-server-url: "/AKfycbwZgC4RNZOiNnylHLbk4rdNmaapEh0rshwLVvY3iV0XYFFw-kLqtg9W23D32UvvX_f2/exec"
