### get notifications
GET http://localhost:8080/api/notifications?pageNumber=0&pageSize=10

### read notifications
POST http://localhost:8080/api/notifications/read
Content-Type: application/json

{
  "keys": [
    "{{notificationKey}}"
  ]
}

### notification alarm
GET http://localhost:8080/api/notifications/alarm