spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    write:
      hikari:
        jdbc-url: jdbc:h2:mem:test;DATABASE_TO_LOWER=true;CASE_INSENSITIVE_IDENTIFIERS=true;MODE=PostgreSQL;
        username: sa
        password:
        poolName: write
        auto-commit: false
    read-only:
      hikari:
        jdbc-url: jdbc:h2:mem:test;DATABASE_TO_LOWER=true;CASE_INSENSITIVE_IDENTIFIERS=true;MODE=PostgreSQL;
        username: sa
        password:
        poolName: read
        auto-commit: false
