spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: local

app:
  slack-alert-url: "https://hooks.slack.com/services/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"

---
spring:
  config:
    activate:
      on-profile: test

app:
  slack-alert-url: "https://hooks.slack.com/services/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"
