spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: local

app:
  image-api-url: "https://script.google.com/macros/s"
  image-creation-path: "/AKfycbwZgC4RNZOiNnylHLbk4rdNmaapEh0rshwLVvY3iV0XYFFw-kLqtg9W23D32UvvX_f2/exec"
  image-deletion-path: "/AKfycbyGL1KnAAUvfc8nSgMcPwQmPO4_gmrb48jWSoepAvAQSmFnTUJcvV3ms3KfRWz1DaEl/exec"
  google-drive-url: "https://drive.usercontent.google.com"

---
spring:
  config:
    activate:
      on-profile: test

app:
  image-api-url: ""
  image-creation-path: ""
  image-deletion-path: ""
  google-drive-url: ""