logging:
  level:
    root: info

server:
  port: 8080
  shutdown: graceful
  error: # default error attribute for prod profile
    include-exception: false # Include the "exception" attribute.
    include-stacktrace: never # When to include a "stacktrace" attribute. possible value is 'always, never, on_param'
    whitelabel.enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  security:
    user:
      name: 'Admin'
      password: '1234'
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - classpath:/application-google.yaml
      - classpath:/application-h2.yaml
      - classpath:/application-slack.yaml

